---
kind: pipeline
name: edge-x86_64
type: docker

#clone:
#  disable: true

platform:
  os: linux
  arch: amd64

steps:
  - name: image
    image: docker:latest
    commands:
      - env
      - ls -l /var/run/docker.sock
      - docker build -t aports-env:$DRONE_COMMIT_SHA dockerfiles/edge/x86_64
    volumes:
      - name: /var/run/docker.sock
        path: /var/run/docker.sock
  - name: build
#    image: strfry/alpine-drone-ci:edge-x86_64
    image: aports-env:$DRONE_COMMIT_SHA
    volumes:
      - name: /var/cache/apk
        path: /var/cache/apk
    commands:
      - ls /var/cache/apk
      - sh scripts/build.sh
    environment:
      GH_TOKEN:
        from_secret: github_token
    pull: always

trigger:
  event:
    - pull_request


#---
#kind: pipeline
#name: edge-aarch64

#clone:
  #disable: true

#platform:
  #os: linux
  #arch: amd64

#steps:
    
  #- name: build
    #image: alpinelinux/alpine-drone-ci:edge-x86_64
    #volumes:
      #- name: docker_sock
        #path: /var/run/docker.sock
      #- name: /usr/bin/qemu-aarch64
        #path: /usr/bin/qemu-aarch64-static
    #pull: never 
    #commands:
      #- sudo sed -i 's,github.com/alpinelinux/aports,github.com/strfry/aports,g' /usr/local/bin/build.sh
      #- sh -x /usr/local/bin/build.sh
    #environment:
      #GH_TOKEN:
        #from_secret: github_token
    #pull: always

#trigger:
  #event:
    #- pull_request
