---
kind: pipeline
name: edge-x86

clone:
  disable: true

platform:
  os: linux
  arch: amd64

steps:
  - name: build
    image: alpinelinux/alpine-drone-ci:edge-x86
    commands:
      - sudo sed -i 's,github.com/alpinelinux/aports,github.com/strfry/aports,g' /usr/local/bin/build.sh
      - cat $(which build.sh)
      - sh -x /usr/local/bin/build.sh
    environment:
      GH_TOKEN:
        from_secret: github_token
    pull: always

trigger:
  event:
    - pull_request


---
kind: pipeline
name: edge-aarch64

clone:
  disable: true

platform:
  os: linux
  arch: amd64

steps:
  - name: patch in qemu-static
    image: docker:latest
    volumes:
      - name: docker_sock
        path: /var/run/docker.sock
    commands:
    - docker build -t runner-aarch64:${DRONE_COMMIT} -f scripts/docker/Dockerfile.aarch64
    
  - name: build
    image: alpinelinux/alpine-drone-ci:edge-aarch64:${DRONE_COMMIT}
    commands:
      - sudo sed -i 's,github.com/alpinelinux/aports,github.com/strfry/aports,g' /usr/local/bin/build.sh
      - sh -x /usr/local/bin/build.sh
    environment:
      GH_TOKEN:
        from_secret: github_token
    pull: always

trigger:
  event:
    - push


