---
kind: pipeline
type: docker
name: edge-x86_64

platform:
  os: linux
  arch: amd64

steps:
  - name: image
    image: docker:latest
    volumes:
      - name: docker_sock
        path: /var/run/docker.sock
    commands: 
      - docker build -t strfry/alpine-drone-ci:edge-x86_64-${DRONE_COMMIT_SHA} dockerfiles/edge/x86_64
  - name: build
    image: strfry/alpine-drone-ci:edge-x86_64-${DRONE_COMMIT_SHA}
    volumes:
      - name: apk_cache
        path: /var/cache/apk
      - name: package_repo
        path: /var/www/alpine
    environment:
      APK_KEY:
        from_secret: apk_build_key
      PACKAGER: alpine-infra@strfry.org
    commands:
      - cp -r /drone/src /home/buildozer/aports
      - sh -x scripts/build.sh
  - name: publish
    image: alpine:latest
    volumes:
      - name: package_repo
        path: /var/www/alpine
    network_mode: bridge
    commands:
      - apk add openssh-client rsync
      - mkdir ~/.ssh && echo -en "$SSH_KEY" > ~/.ssh/id_ed25519 && chmod 600 ~/.ssh/id_ed25519
      - rsync -r -e "ssh -o StrictHostKeyChecking=no" /var/www/alpine/packages upload@upload-alpine.strfry.org:/var/www/alpine
    environment:
      SSH_KEY:
        from_secret: ssh_upload_key
    when:
      branch:
      - master
trigger:
  event:
    - push

volumes:
- name: docker_sock
  host:
    path: /var/run/docker.sock
- name: apk_cache
  host:
    path: /var/cache/apk
- name: package_repo
  host:
    path: /var/www/alpine
