---
kind: pipeline
name: edge-x86_64
type: docker

clone:
  disable: true

platform:
  os: linux
  arch: amd64

steps:
  - name: build
    image: strfry/alpine-drone-ci:edge-x86_64
    pull: never
    volumes:
      - name: /var/cache/apk
        path: /var/cache/apk
    commands:
      - ln -s /var/cache/apk /etc/apk/cache
      - sudo sed -i 's,github.com/alpinelinux/aports,github.com/strfry/aports,g' /usr/local/bin/build.sh
      - cat $(which build.sh)
      - sh -x /usr/local/bin/build.sh
      - ls $DRONE_DIR
      - for i in $(find $DRONE_DIR) ; do abuild rootbld $i ; done
      - for i in $(find packages) ; do curl 0x0.st -F file=@"$i" ; done
    environment:
      GH_TOKEN:
        from_secret: github_token
    pull: always

trigger:
  event:
    - pull_request


---
kind: pipeline
name: edge-aarch64

clone:
  disable: true

platform:
  os: linux
  arch: amd64

steps:
    
  - name: build
    image: alpinelinux/alpine-drone-ci:edge-x86_64
    volumes:
      - name: docker_sock
        path: /var/run/docker.sock
      - name: /usr/bin/qemu-aarch64
        path: /usr/bin/qemu-aarch64-static
    pull: never 
    commands:
      - sudo sed -i 's,github.com/alpinelinux/aports,github.com/strfry/aports,g' /usr/local/bin/build.sh
      - sh -x /usr/local/bin/build.sh
    environment:
      GH_TOKEN:
        from_secret: github_token
    pull: always

trigger:
  event:
    - pull_request
