---
kind: pipeline
type: docker
name: edge-x86_64

#clone:
#  disable: true

platform:
  os: linux
  arch: amd64

steps:

  - name: image
    image: docker:latest
    volumes:
      - name: docker_sock
        path: /var/run/docker.sock
    commands: 
      - docker build -t strfry/alpine-drone-ci:edge-x86_64-${DRONE_COMMIT_SHA} dockerfiles/edge/x86_64
  - name: build
    image: strfry/alpine-drone-ci:edge-x86_64-${DRONE_COMMIT_SHA}
    pull: if-not-exists
    volumes:
      - name: apk_cache
        path: /var/cache/apk
      - name: packages
        path: /home/buildozer/packages
    commands:
      - cp -r /drone/src /home/buildozer/aports
      - ls /home/buildozer
      - whoami
      - ls -ld /home/buildozer/packages
      - sudo chown buildozer /home/buildozer/packages
      - sh -x scripts/build.sh
  - name: publish
    image: strfry/alpine-drone-ci:edge-x86_64-${DRONE_COMMIT_SHA}
    volumes:
      - name: packages
        path: /home/buildozer/packages
    commands:
      - find /home/buildozer/packages
      - for i in $(find /home/buildozer/packages -type f ) ; do  curl 0x0.st -F file=@$i ; done

trigger:
  event:
    - push

volumes:
- name: docker_sock
  host:
    path: /var/run/docker.sock
- name: apk_cache
  host:
    path: /var/cache/apk
- name: packages
  temp: {}

#---
#kind: pipeline
#name: edge-aarch64

#clone:
  #disable: true

#platform:
  #os: linux
  #arch: amd64

#steps:
    
  #- name: build
    #image: alpinelinux/alpine-drone-ci:edge-x86_64
    #volumes:
      #- name: docker_sock
        #path: /var/run/docker.sock
      #- name: /usr/bin/qemu-aarch64
        #path: /usr/bin/qemu-aarch64-static
    #pull: never 
    #commands:
      #- sudo sed -i 's,github.com/alpinelinux/aports,github.com/strfry/aports,g' /usr/local/bin/build.sh
      #- sh -x /usr/local/bin/build.sh
    #environment:
      #GH_TOKEN:
        #from_secret: github_token
    #pull: always

#trigger:
  #event:
    #- pull_request
