---
kind: pipeline
name: edge-x86

clone:
  disable: true

platform:
  os: linux
  arch: amd64

steps:
  - name: build
    image: alpinelinux/alpine-drone-ci:edge-x86
    commands:
      - echo $(which build.sh)
      - cat $(which build.sh)
    environment:
      GH_TOKEN:
        from_secret: github_token
    pull: always

trigger:
  event:
    - pull_request


