# docker run --rm --privileged multiarch/qemu-user-static:register

FROM alpinelinux/alpine-drone-ci:edge-aarch64

#RUN apk add qemu-aarch64

#FROM multiarch/qemu-user-static
# COPY /usr/bin/qemu-aarch64 /usr/bin/qemu-aarch64-static

